services:
  web:
    restart: always
    build: ./webserver
    container_name: "web_market"
    command: ["npm", "run", "dev"]
    tty: true
    volumes:
      - ./webserver/app:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - 3000:3000
