services:
  web:
    restart: always
    build:
      context: ./webserver
      target: development
    container_name: "web_market"
    # command: ["npm", "run", "dev"]
    working_dir: /usr/src/app
    tty: true
    volumes:
      - ./webserver/app:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - 3000:3000
